version: '3.6'

x-environment: &environment
  POSTGRES_DB: demo
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_HOST: db

services:
  db:
    image: mdillon/postgis
    container_name: db
    environment:
      <<: *environment
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  django:
    build: .
    container_name: django
    restart: on-failure
    environment:
      <<: *environment
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db



volumes:
  postgres_data: