# Generated by Django 3.2.8 on 2021-10-16 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='centerimages',
            options={'verbose_name_plural': 'Center Images'},
        ),
    ]
